[package]
name = "dioxus-ui-web-demo"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
dioxus-ui = { workspace = true, features = ["accordion", "alert", "alert-dialog", "aspect-ratio", "avatar", "badge", "breadcrumb", "button", "button-group", "calendar", "carousel", "card", "checkbox", "collapsible", "command", "combobox", "context-menu", "data-table", "date-picker", "dialog", "drawer", "dropdown", "empty", "field", "hover-card", "input", "input-group", "item", "kbd", "label", "menubar", "native-select", "navigation-menu", "pagination", "popover", "progress", "radio-group", "resizable", "scroll-area", "select", "separator", "sheet", "sidebar", "skeleton", "slider", "sonner", "spinner", "switch", "table", "tabs", "textarea", "toggle", "toggle-group", "toast", "tooltip", "typography"] }
