[package]
name = "dioxus-ui-web-demo"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
dioxus-ui = { workspace = true, features = ["accordion", "alert", "alert-dialog", "avatar", "badge", "button", "card", "checkbox", "dialog", "drawer", "dropdown", "hover-card", "input", "label", "pagination", "popover", "progress", "radio-group", "select", "separator", "sheet", "skeleton", "slider", "spinner", "switch", "table", "tabs", "textarea", "toggle", "toggle-group", "tooltip"] }
