// Generated by `npm run site:catalog` from scripts/docs-catalog-builder.mjs.
// Do not edit by hand; `npm run verify:site-catalog` fails when it is stale.

pub struct Category {
  pub id: &'static str,
  pub label: &'static str,
  pub components: &'static [Component],
}

pub struct Component {
  pub slug: &'static str,
  pub title: &'static str,
  pub description: &'static str,
  pub feature: &'static str,
}

pub const CATEGORIES: &[Category] = &[
  Category {
    id: "actions",
    label: "Actions",
    components: &[
      Component {
        slug: "button",
        title: "Button",
        description: "Button component with variants, sizes, and density-aware spacing.",
        feature: "button",
      },
      Component {
        slug: "button-group",
        title: "Button Group",
        description: "Button Group component for grouped command buttons.",
        feature: "button-group",
      },
      Component {
        slug: "command",
        title: "Command",
        description: "Controlled command palette parts with active descendant semantics.",
        feature: "command",
      },
      Component {
        slug: "kbd",
        title: "Kbd",
        description: "Styled keyboard shortcut hint.",
        feature: "kbd",
      },
      Component {
        slug: "toggle",
        title: "Toggle",
        description: "Toggle component for controlled pressed button states.",
        feature: "toggle",
      },
      Component {
        slug: "toggle-group",
        title: "Toggle Group",
        description: "Toggle Group component for grouped single or multiple pressed states.",
        feature: "toggle-group",
      },
    ],
  },
  Category {
    id: "forms",
    label: "Forms",
    components: &[
      Component {
        slug: "calendar",
        title: "Calendar",
        description: "Calendar components backed by pure date grid primitives.",
        feature: "calendar",
      },
      Component {
        slug: "checkbox",
        title: "Checkbox",
        description: "Checkbox component with checked and disabled states.",
        feature: "checkbox",
      },
      Component {
        slug: "date-picker",
        title: "Date Picker",
        description: "Date Picker trigger, value, and popover content parts for composing Calendar.",
        feature: "date-picker",
      },
      Component {
        slug: "field",
        title: "Field",
        description: "Form field layout composition parts.",
        feature: "field",
      },
      Component {
        slug: "input",
        title: "Input",
        description: "Input component with disabled and invalid states.",
        feature: "input",
      },
      Component {
        slug: "input-group",
        title: "Input Group",
        description: "Input Group component for addons, controls, and actions around inputs.",
        feature: "input-group",
      },
      Component {
        slug: "input-otp",
        title: "Input OTP",
        description: "Input OTP component with controlled visual slots and native input support.",
        feature: "input-otp",
      },
      Component {
        slug: "label",
        title: "Label",
        description: "Label component for associating text with form controls.",
        feature: "label",
      },
      Component {
        slug: "native-select",
        title: "Native Select",
        description: "Styled native select, optgroup, and option components.",
        feature: "native-select",
      },
      Component {
        slug: "radio-group",
        title: "Radio Group",
        description: "Radio Group component for single-choice grouped selection.",
        feature: "radio-group",
      },
      Component {
        slug: "select",
        title: "Select",
        description: "Select components backed by primitive configuration types.",
        feature: "select",
      },
      Component {
        slug: "slider",
        title: "Slider",
        description: "Slider component for controlled horizontal numeric values.",
        feature: "slider",
      },
      Component {
        slug: "switch",
        title: "Switch",
        description: "Switch component with checked and disabled states.",
        feature: "switch",
      },
      Component {
        slug: "textarea",
        title: "Textarea",
        description: "Textarea component with disabled and invalid states.",
        feature: "textarea",
      },
    ],
  },
  Category {
    id: "overlays",
    label: "Overlays",
    components: &[
      Component {
        slug: "alert-dialog",
        title: "Alert Dialog",
        description: "Alert dialog confirmation components backed by dialog primitive configuration.",
        feature: "alert-dialog",
      },
      Component {
        slug: "combobox",
        title: "Combobox",
        description: "Controlled searchable selection parts backed by popover primitive configuration.",
        feature: "combobox",
      },
      Component {
        slug: "context-menu",
        title: "Context Menu",
        description: "Controlled context menu parts backed by dropdown primitive configuration.",
        feature: "context-menu",
      },
      Component {
        slug: "dialog",
        title: "Dialog",
        description: "Dialog overlay components backed by primitive configuration types.",
        feature: "dialog",
      },
      Component {
        slug: "drawer",
        title: "Drawer",
        description: "Mobile-oriented bottom drawer components backed by dialog primitive configuration.",
        feature: "drawer",
      },
      Component {
        slug: "dropdown",
        title: "Dropdown",
        description: "Dropdown menu components backed by primitive configuration types.",
        feature: "dropdown",
      },
      Component {
        slug: "hover-card",
        title: "Hover Card",
        description: "Controlled rich preview content backed by popover primitive configuration.",
        feature: "hover-card",
      },
      Component {
        slug: "menubar",
        title: "Menubar",
        description: "Controlled menubar parts backed by dropdown primitive configuration.",
        feature: "menubar",
      },
      Component {
        slug: "popover",
        title: "Popover",
        description: "Popover content components backed by primitive configuration types.",
        feature: "popover",
      },
      Component {
        slug: "sheet",
        title: "Sheet",
        description: "Side sheet overlay components backed by dialog primitive configuration.",
        feature: "sheet",
      },
      Component {
        slug: "tooltip",
        title: "Tooltip",
        description: "Tooltip content component backed by primitive configuration types.",
        feature: "tooltip",
      },
    ],
  },
  Category {
    id: "navigation",
    label: "Navigation",
    components: &[
      Component {
        slug: "breadcrumb",
        title: "Breadcrumb",
        description: "Semantic breadcrumb navigation composition parts.",
        feature: "breadcrumb",
      },
      Component {
        slug: "navigation-menu",
        title: "Navigation Menu",
        description: "Controlled navigation menu parts with navigation semantics.",
        feature: "navigation-menu",
      },
      Component {
        slug: "pagination",
        title: "Pagination",
        description: "Pagination component with link, item, and ellipsis parts.",
        feature: "pagination",
      },
      Component {
        slug: "sidebar",
        title: "Sidebar",
        description: "Controlled sidebar shell and navigation composition parts.",
        feature: "sidebar",
      },
      Component {
        slug: "steps",
        title: "Steps",
        description: "Styled numbered steps with complete, current, and upcoming states.",
        feature: "steps",
      },
      Component {
        slug: "tabs",
        title: "Tabs",
        description: "Tabs components with controlled active state.",
        feature: "tabs",
      },
    ],
  },
  Category {
    id: "layout",
    label: "Layout",
    components: &[
      Component {
        slug: "accordion",
        title: "Accordion",
        description: "Accordion components with controlled open state.",
        feature: "accordion",
      },
      Component {
        slug: "aspect-ratio",
        title: "Aspect Ratio",
        description: "Fixed-ratio media and content slot.",
        feature: "aspect-ratio",
      },
      Component {
        slug: "card",
        title: "Card",
        description: "Card component with header, content, and footer parts.",
        feature: "card",
      },
      Component {
        slug: "carousel",
        title: "Carousel",
        description: "Controlled carousel composition parts and index helpers.",
        feature: "carousel",
      },
      Component {
        slug: "collapsible",
        title: "Collapsible",
        description: "Collapsible component for controlled disclosure content.",
        feature: "collapsible",
      },
      Component {
        slug: "direction",
        title: "Direction",
        description: "Direction component for scoped native ltr/rtl text direction.",
        feature: "direction",
      },
      Component {
        slug: "indicator",
        title: "Indicator",
        description: "Styled corner indicator wrapper and placed item.",
        feature: "indicator",
      },
      Component {
        slug: "item",
        title: "Item",
        description: "Generic list item composition parts.",
        feature: "item",
      },
      Component {
        slug: "resizable",
        title: "Resizable",
        description: "Controlled resizable panel group, panel, and handle parts.",
        feature: "resizable",
      },
      Component {
        slug: "scroll-area",
        title: "Scroll Area",
        description: "Native scroll area wrapper with styled viewport and scrollbar parts.",
        feature: "scroll-area",
      },
      Component {
        slug: "separator",
        title: "Separator",
        description: "Separator component for visual or semantic content division.",
        feature: "separator",
      },
    ],
  },
  Category {
    id: "data-display",
    label: "Data Display",
    components: &[
      Component {
        slug: "avatar",
        title: "Avatar",
        description: "Avatar component with image and fallback parts.",
        feature: "avatar",
      },
      Component {
        slug: "badge",
        title: "Badge",
        description: "Badge component with static status variants.",
        feature: "badge",
      },
      Component {
        slug: "chart",
        title: "Chart",
        description: "Source-copy friendly SVG chart composition parts.",
        feature: "chart",
      },
      Component {
        slug: "data-table",
        title: "Data Table",
        description: "Controlled Data Table composition parts and state helpers.",
        feature: "data-table",
      },
      Component {
        slug: "empty",
        title: "Empty",
        description: "Empty-state layout composition parts.",
        feature: "empty",
      },
      Component {
        slug: "progress",
        title: "Progress",
        description: "Progress component with accessible value semantics.",
        feature: "progress",
      },
      Component {
        slug: "stat",
        title: "Stat",
        description: "Styled statistic group with title, value, description, and figure.",
        feature: "stat",
      },
      Component {
        slug: "table",
        title: "Table",
        description: "Table component with styled table parts.",
        feature: "table",
      },
      Component {
        slug: "timeline",
        title: "Timeline",
        description: "Styled ordered timeline with time, marker, and content parts.",
        feature: "timeline",
      },
      Component {
        slug: "typography",
        title: "Typography",
        description: "Styled semantic typography parts.",
        feature: "typography",
      },
    ],
  },
  Category {
    id: "feedback",
    label: "Feedback",
    components: &[
      Component {
        slug: "alert",
        title: "Alert",
        description: "Alert component with title and description parts.",
        feature: "alert",
      },
      Component {
        slug: "skeleton",
        title: "Skeleton",
        description: "Skeleton component for loading placeholders.",
        feature: "skeleton",
      },
      Component {
        slug: "sonner",
        title: "Sonner",
        description: "Opinionated toast notification parts and queue helpers.",
        feature: "sonner",
      },
      Component {
        slug: "spinner",
        title: "Spinner",
        description: "Spinner component for loading status feedback.",
        feature: "spinner",
      },
      Component {
        slug: "status",
        title: "Status",
        description: "Styled status dot with an optional accessible label.",
        feature: "status",
      },
      Component {
        slug: "toast",
        title: "Toast",
        description: "Controlled toast notification parts and queue helpers.",
        feature: "toast",
      },
    ],
  },
  Category {
    id: "messaging",
    label: "Messaging",
    components: &[
      Component {
        slug: "attachment",
        title: "Attachment",
        description: "Attachment component for provider-neutral file preview rows and actions.",
        feature: "attachment",
      },
      Component {
        slug: "bubble",
        title: "Bubble",
        description: "Bubble component for provider-neutral message surfaces and reactions.",
        feature: "bubble",
      },
      Component {
        slug: "marker",
        title: "Marker",
        description: "Marker component for inline status, bordered rows, and labeled separators.",
        feature: "marker",
      },
      Component {
        slug: "message",
        title: "Message",
        description: "Message component for provider-neutral chat row layout.",
        feature: "message",
      },
      Component {
        slug: "message-scroller",
        title: "Message Scroller",
        description: "Controlled message scroller composition parts with pure scroll intent helpers.",
        feature: "message-scroller",
      },
    ],
  },
];
