// Generated by `npm run site:catalog` from crates/dioxus-shadcn-cli/themes/.
// Do not edit by hand; `npm run verify:site-catalog` fails when it is stale.

pub struct Theme {
  pub name: &'static str,
  pub title: &'static str,
  pub dark: bool,
}

pub const THEMES: &[Theme] = &[
  Theme { name: "abyss", title: "Abyss", dark: true },
  Theme { name: "acid", title: "Acid", dark: false },
  Theme { name: "aqua", title: "Aqua", dark: true },
  Theme { name: "autumn", title: "Autumn", dark: false },
  Theme { name: "black", title: "Black", dark: true },
  Theme { name: "bumblebee", title: "Bumblebee", dark: false },
  Theme { name: "business", title: "Business", dark: true },
  Theme { name: "caramellatte", title: "Caramellatte", dark: false },
  Theme { name: "cmyk", title: "Cmyk", dark: false },
  Theme { name: "coffee", title: "Coffee", dark: true },
  Theme { name: "corporate", title: "Corporate", dark: false },
  Theme { name: "cupcake", title: "Cupcake", dark: false },
  Theme { name: "cyberpunk", title: "Cyberpunk", dark: false },
  Theme { name: "dim", title: "Dim", dark: true },
  Theme { name: "dracula", title: "Dracula", dark: true },
  Theme { name: "emerald", title: "Emerald", dark: false },
  Theme { name: "fantasy", title: "Fantasy", dark: false },
  Theme { name: "forest", title: "Forest", dark: true },
  Theme { name: "garden", title: "Garden", dark: false },
  Theme { name: "halloween", title: "Halloween", dark: true },
  Theme { name: "lemonade", title: "Lemonade", dark: false },
  Theme { name: "lofi", title: "Lofi", dark: false },
  Theme { name: "luxury", title: "Luxury", dark: true },
  Theme { name: "night", title: "Night", dark: true },
  Theme { name: "nord", title: "Nord", dark: false },
  Theme { name: "pastel", title: "Pastel", dark: false },
  Theme { name: "retro", title: "Retro", dark: false },
  Theme { name: "silk", title: "Silk", dark: false },
  Theme { name: "sunset", title: "Sunset", dark: true },
  Theme { name: "synthwave", title: "Synthwave", dark: true },
  Theme { name: "valentine", title: "Valentine", dark: false },
  Theme { name: "winter", title: "Winter", dark: false },
  Theme { name: "wireframe", title: "Wireframe", dark: false },
];
