[package]
name = "dioxus-shadcn-cli"
description = "Command-line tool for adding dioxus-shadcn components to Dioxus projects."
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[[bin]]
name = "dxui"
path = "src/main.rs"

[dependencies]
dioxus-shadcn-core.workspace = true
serde_json.workspace = true
similar = "3"

[build-dependencies]
serde_json.workspace = true

[dev-dependencies]
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full"] }
