#!/usr/bin/env node
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { buildDocsCatalog } from "./docs-catalog-builder.mjs";

// Writes the site's catalog from the docs catalog builder (RFC 0052), so the
// site sidebar, catalog.md, and routes.md share one source, and the site's
// theme list and stylesheet from the CLI's theme presets (RFC 0057).
// `--check` fails when a committed file is stale.
const repoRoot = dirname(dirname(fileURLToPath(import.meta.url)));
const themesDir = join(repoRoot, "crates/dioxus-shadcn-cli/themes");

const rustString = (value) => JSON.stringify(value);

function renderSiteCatalog() {
  const { catalog, catalogCategories } = buildDocsCatalog({ repoRoot });
  const categories = catalogCategories.map((category) => {
    const components = catalog
      .filter((item) => item.category === category.id)
      .sort((left, right) => left.title.localeCompare(right.title))
      .map(
        (item) =>
          `      Component {\n` +
          `        slug: ${rustString(item.slug)},\n` +
          `        title: ${rustString(item.title)},\n` +
          `        description: ${rustString(item.description)},\n` +
          `        feature: ${rustString(item.crate_feature)},\n` +
          `      },\n`,
      )
      .join("");
    return (
      `  Category {\n` +
      `    id: ${rustString(category.id)},\n` +
      `    label: ${rustString(category.label)},\n` +
      `    components: &[\n${components}    ],\n` +
      `  },\n`
    );
  });

  return (
    `// Generated by \`npm run site:catalog\` from scripts/docs-catalog-builder.mjs.\n` +
    `// Do not edit by hand; \`npm run verify:site-catalog\` fails when it is stale.\n\n` +
    `pub struct Category {\n` +
    `  pub id: &'static str,\n` +
    `  pub label: &'static str,\n` +
    `  pub components: &'static [Component],\n` +
    `}\n\n` +
    `pub struct Component {\n` +
    `  pub slug: &'static str,\n` +
    `  pub title: &'static str,\n` +
    `  pub description: &'static str,\n` +
    `  pub feature: &'static str,\n` +
    `}\n\n` +
    `pub const CATEGORIES: &[Category] = &[\n${categories.join("")}];\n`
  );
}

function themePresets() {
  return readdirSync(themesDir)
    .filter((file) => file.endsWith(".css"))
    .sort()
    .map((file) => {
      const css = readFileSync(join(themesDir, file), "utf8");
      return { name: file.replace(/\.css$/, ""), css, dark: css.includes("color-scheme: dark;") };
    });
}

function renderSiteThemes(presets) {
  const themes = presets
    .map((preset) => {
      const title = preset.name.charAt(0).toUpperCase() + preset.name.slice(1);
      return `  Theme { name: ${rustString(preset.name)}, title: ${rustString(title)}, dark: ${preset.dark} },\n`;
    })
    .join("");
  return (
    `// Generated by \`npm run site:catalog\` from crates/dioxus-shadcn-cli/themes/.\n` +
    `// Do not edit by hand; \`npm run verify:site-catalog\` fails when it is stale.\n\n` +
    `pub struct Theme {\n` +
    `  pub name: &'static str,\n` +
    `  pub title: &'static str,\n` +
    `  pub dark: bool,\n` +
    `}\n\n` +
    `pub const THEMES: &[Theme] = &[\n${themes}];\n`
  );
}

function renderSiteThemeCss(presets) {
  return (
    `/* Generated by \`npm run site:catalog\` from crates/dioxus-shadcn-cli/themes/.\n` +
    `   Do not edit by hand; \`npm run verify:site-catalog\` fails when it is stale. */\n\n` +
    presets.map((preset) => preset.css).join("\n")
  );
}

const presets = themePresets();
const outputs = [
  ["site/src/catalog.rs", renderSiteCatalog()],
  ["site/src/themes.rs", renderSiteThemes(presets)],
  ["site/assets/themes.css", renderSiteThemeCss(presets)],
];
if (process.argv.includes("--check")) {
  for (const [relativeOutput, expected] of outputs) {
    let actual = "";
    try {
      actual = readFileSync(join(repoRoot, relativeOutput), "utf8");
    } catch {
      actual = "";
    }
    if (actual !== expected) {
      console.error(`site catalog is out of date: run \`npm run site:catalog\` and commit ${relativeOutput}`);
      process.exitCode = 1;
    }
  }
  if (process.exitCode !== 1) {
    console.log("site catalog verification passed");
  }
} else {
  for (const [relativeOutput, expected] of outputs) {
    writeFileSync(join(repoRoot, relativeOutput), expected);
    console.log(`wrote ${relativeOutput}`);
  }
}
