#!/usr/bin/env node
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { buildDocsCatalog } from "./docs-catalog-builder.mjs";

// Writes the site's catalog from the docs catalog builder (RFC 0052), so the
// site sidebar, catalog.md, and routes.md share one source. `--check` fails
// when the committed file is stale.
const repoRoot = dirname(dirname(fileURLToPath(import.meta.url)));
const outputPath = join(repoRoot, "site/src/catalog.rs");
const relativeOutput = "site/src/catalog.rs";

const rustString = (value) => JSON.stringify(value);

function renderSiteCatalog() {
  const { catalog, catalogCategories } = buildDocsCatalog({ repoRoot });
  const categories = catalogCategories.map((category) => {
    const components = catalog
      .filter((item) => item.category === category.id)
      .sort((left, right) => left.title.localeCompare(right.title))
      .map(
        (item) =>
          `      Component {\n` +
          `        slug: ${rustString(item.slug)},\n` +
          `        title: ${rustString(item.title)},\n` +
          `        description: ${rustString(item.description)},\n` +
          `        feature: ${rustString(item.crate_feature)},\n` +
          `      },\n`,
      )
      .join("");
    return (
      `  Category {\n` +
      `    id: ${rustString(category.id)},\n` +
      `    label: ${rustString(category.label)},\n` +
      `    components: &[\n${components}    ],\n` +
      `  },\n`
    );
  });

  return (
    `// Generated by \`npm run site:catalog\` from scripts/docs-catalog-builder.mjs.\n` +
    `// Do not edit by hand; \`npm run verify:site-catalog\` fails when it is stale.\n\n` +
    `pub struct Category {\n` +
    `  pub id: &'static str,\n` +
    `  pub label: &'static str,\n` +
    `  pub components: &'static [Component],\n` +
    `}\n\n` +
    `pub struct Component {\n` +
    `  pub slug: &'static str,\n` +
    `  pub title: &'static str,\n` +
    `  pub description: &'static str,\n` +
    `  pub feature: &'static str,\n` +
    `}\n\n` +
    `pub const CATEGORIES: &[Category] = &[\n${categories.join("")}];\n`
  );
}

const expected = renderSiteCatalog();
if (process.argv.includes("--check")) {
  let actual = "";
  try {
    actual = readFileSync(outputPath, "utf8");
  } catch {
    actual = "";
  }
  if (actual !== expected) {
    console.error(`site catalog is out of date: run \`npm run site:catalog\` and commit ${relativeOutput}`);
    process.exitCode = 1;
  } else {
    console.log("site catalog verification passed");
  }
} else {
  writeFileSync(outputPath, expected);
  console.log(`wrote ${relativeOutput}`);
}
