[package]
name = "dioxus-ui"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[features]
default = []
alert = []
alert-dialog = ["dioxus-ui-primitives/dialog"]
aspect-ratio = []
avatar = []
badge = []
breadcrumb = []
button = []
calendar = []
carousel = []
card = []
input = []
item = []
kbd = []
textarea = []
label = []
menubar = ["dioxus-ui-primitives/dropdown"]
native-select = []
navigation-menu = ["dioxus-ui-primitives/popover"]
checkbox = []
command = []
combobox = ["dioxus-ui-primitives/popover"]
context-menu = ["dioxus-ui-primitives/dropdown"]
data-table = []
date-picker = ["dioxus-ui-primitives/popover"]
pagination = []
separator = []
sheet = ["dioxus-ui-primitives/dialog"]
sidebar = []
skeleton = []
slider = []
sonner = []
spinner = []
switch = []
table = []
tabs = []
toggle = []
toggle-group = []
toast = []
typography = []
accordion = []
dialog = ["dioxus-ui-primitives/dialog"]
drawer = ["dioxus-ui-primitives/dialog"]
dropdown = ["dioxus-ui-primitives/dropdown"]
empty = []
field = []
hover-card = ["dioxus-ui-primitives/popover"]
popover = ["dioxus-ui-primitives/popover"]
progress = []
radio-group = []
resizable = []
select = ["dioxus-ui-primitives/select"]
scroll-area = []
tooltip = ["dioxus-ui-primitives/tooltip"]

[dependencies]
dioxus.workspace = true
dioxus-ui-core.workspace = true
dioxus-ui-primitives.workspace = true
