[package]
name = "dioxus-ui"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[features]
default = []
badge = []
button = []
input = []
textarea = []
label = []
checkbox = []
separator = []
skeleton = []
switch = []
tabs = []
accordion = []
dialog = ["dioxus-ui-primitives/dialog"]
dropdown = ["dioxus-ui-primitives/dropdown"]
popover = ["dioxus-ui-primitives/popover"]
select = ["dioxus-ui-primitives/select"]
tooltip = ["dioxus-ui-primitives/tooltip"]

[dependencies]
dioxus.workspace = true
dioxus-ui-core.workspace = true
dioxus-ui-primitives.workspace = true
