[package]
name = "dioxus-ui-preview-states"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
dioxus = { workspace = true }
dioxus-shadcn = { workspace = true, features = ["accordion", "alert-dialog", "attachment", "bubble", "button", "button-group", "calendar", "carousel", "chart", "checkbox", "collapsible", "combobox", "command", "context-menu", "date-picker", "dialog", "direction", "dropdown", "field", "hover-card", "input", "input-group", "menubar", "input-otp", "label", "marker", "message", "message-scroller", "native-select", "navigation-menu", "pagination", "popover", "progress", "radio-group", "resizable", "select", "sidebar", "slider", "sonner", "switch", "table", "tabs", "textarea", "toast", "toggle", "toggle-group", "tooltip", "diff", "rating", "number-input", "tags-input", "file-input", "swap", "fab", "theme-controller", "menu", "mockup"] }
serde_json = { workspace = true }
