[package]
name = "dioxus-ui-preview-states"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
dioxus = { workspace = true }
dioxus-ui = { workspace = true, features = ["alert-dialog", "attachment", "bubble", "button", "button-group", "calendar", "chart", "collapsible", "combobox", "date-picker", "dialog", "direction", "input-group", "input-otp", "marker", "message", "message-scroller", "popover", "select", "sonner", "toast", "tooltip"] }
